### ISSUE TITLE
Patching "Monaco" with Fira Ligature characters

### ISSUE THREAD

**Issue by carlca** [powerline/fonts#255]
macOS 10.12.6
MS VSCode Insiders 1.17.0
iTerm2 v3.1.2

Hello, I'm still a newbie when it comes to advanced font issues, so please be gentle with me! I'm using VSCode for coding with my preferred font Monaco. I also have this font in its Powerline incarnation in use in iTerm2 where I have it display the fancier aspects of ZSH very nicely.

I have seen and like the Ligature features of the Fira Code font but I don't particularly like the standard character images. My ideal solution would be the "Monaco for Powerline" font with characters such as the `>=` and `:=` patched with the Fira Code ligature characters.

My research has led me to discover that there is a tool called "Font Patcher" which sounds suspiciously like the answer to my wishes, but I still haven't discovered instructions suitable for a beginner such as I to make use of it.

Can anyone tell me if what I am asking is actually possible and how to do it?

Assuming there are no legal issues in the way I would naturally make the successful outcome of my ventures publically available. Thanks in advance.

**Comment by ZyX-I** [comment]
[Fontpatcher](https://github.com/powerline/fontpatcher) is a tool which patches some vector fonts with powerline characters. The problem is that author of the fontpatcher is nowhere near and the only thing font patcher was ever supposed to do is *adding new glyphs*, based on what I know ligatures are a very different matter. You may want to read something on fontforge which is a dependency of fontpatcher instead.
