### ISSUE TITLE
Weird character shows when executing commands or pressing CTRL + C

### ISSUE THREAD

**Issue by johannesjo** [powerline/fonts#284]
For example
```
$echo "a" 
kecho\a
```
<img src="https://cdn.pbrd.co/images/HlOrpcS.png">

**Comment by ZyX-I** [comment]
This problem cannot possibly be caused by a font otherwise you would not be able to copy those weird characters around. If you think it is you need at least tell which of the fonts maintained here you are using *and* that certain other font does not show this particular problem (using non-patched font with some kind of powerline theme *will* cause some problems, but they should only happen where powerline arrows are expected).

**Comment by johannesjo** [comment]
It was not actually a powerline issue, they only made it visible for some reason. The issue was this line:
```
export TERM=screen-256color
```
